name: Generate Article Index

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate index.json
        run: |
          echo "Generating index.json..."
          files=$(ls *.md articles/*.md | jq -R . | jq -s .)
          echo $files | jq . > index.json

      - name: Commit and Push index.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.json
          git commit -m "Auto-update index.json" || exit 0
          git push
