name: Generate Index

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for creation dates
          token: ${{ secrets.GH_PAT }}  # Use PAT for write access

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate index.json
        run: |
          node ./scripts/generate-index.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.json
          # Check if there are changes to commit
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update index.json" && git push)
