name: Generate Article Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Authenticate checkout with PAT

      - name: Generate index.json
        run: |
          echo "Generating index.json..."
          files=$(find . -maxdepth 1 -type f -name "*.md" | sed 's|./||' | jq -R . | jq -s .)
          echo $files | jq . > index.json
          cat index.json

      - name: Commit and Push index.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use PAT for auth
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.json
          git commit -m "Auto-update index.json" || exit 0
          git push origin HEAD:main  # Now uses the authenticated origin
