name: Generate Article Index

on:
  push:
    branches:
      - main  # Runs when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate index.json
        run: |
          echo "Generating index.json..."
          files=$(find . -maxdepth 1 -type f -name "*.md" | sed 's|./||' | jq -R . | jq -s .)
          echo $files | jq . > index.json
          cat index.json  # Print the output for debugging

      - name: Commit and Push index.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.json
          git commit -m "Auto-update index.json" || exit 0
          git push
